#!groovy


node {
	echo "Start User Manager Project Pipline"
	
	stage ("Get Source Code from Git and Build and Unit Test") {
		build 'User Manager Build'
	}
	
	stage ("Build Docker Image") {
	    build 'Docker Build'
	}
	
	stage ("Deploy on local Test Server") {
	    build 'Start Local Application'
	}
	
	stage ("Integrate Test") {
		build 'User Manager Integration test'
	}
	
	stage ("Docker Publish") {
		build 'Docker Publish'
	}
	
	echo "Pipeline Completed"
}